let suggestions = [
  "Manchester United's 7-0 defeat",
  "Eaglets crash out of U-17 AFCON, Burkina Faso progresses ",
  "Frank Lampard rescues Chelsea from relegation",
  "Climate change",
  "UN on Climate change",
  "I want to rest - Buhari ",
  "Tinubu's swearing in on May 29",
  "Putin visits South Africa",
  "Jamb reschedules exams",
  "Election petition tribunal postpones hearing to May 17",
  "Peter Obi",
  "Atiku storms petition tribunal court (EPTC)",
  "NAFDAC bans importation of noodles",
  "Road map for Front End Designer 2023",
  "ASUU chair on Buhari's loan",
  "Adeleke wins Supreme court case",
  "Innoson awards N3M scholarship to female Anambra indigene",
  "Chat GPT introduces Monica extension on Google",
  "UTME Results 2023 out",
  "Overall Best Student UTME 2023",
  "Russian/ Ukraine war",
  "Giannis feels disrespected, shares post on social media",
  "More Nigerians return home, Sudan war continues",
  "Jamie Foxx in critical condition, Family prepares for worst",
  "Nnamdi Kanu's release",
  "Elon Musk hires new Twitter CE0",
  "Tiwa Savage at King Charles' Coronation",
  "Lecturers on the chat GPT spree",
  "Uyo fashion week 2023",
  "Afang vs Eguisi",
  "NCC announces unified code for all telecom networks",
  "Uyo fashion week 2023",
];
