let suggestions = [
  "Manchester United's 7-0 defeat",
  "Eaglets crash out of U-17 AFCON, Burkina Faso progresses ",
  "Frank Lampard rescues Chelsea from relegation",
  "Climate change",
  "UN on Climate change",
  "I want to rest - Buhari ",
  "Tinubu's swearing in on May 29",
  "Putin visits South Africa",
  "Jamb reschedules exams",
  "Election petition tribunal postpones hearing to May 17",
  "Peter Obi",
  "Atiku storms petition tribunal court (EPTC)",
  "NAFDAC bans importation of noodles",
  "Road map for Front End Designer 2023",
  "ASUU chair on Buhari's loan",
  "Adeleke wins Supreme court case",
  "Innoson awards N3M scholarship to female Anambra indigene",
  "Chat GPT introduces Monica extension on Google",
  "UTME Results 2023 out",
  "Overall Best Student UTME 2023",
  "Russian/ Ukraine war",
  "Giannis feels disrespected, shares post on social media",
  "More Nigerians return home, Sudan war continues",
  "Jamie Foxx in critical condition, Family prepares for worst",
  "Nnamdi Kanu's release",
  "Elon Musk hires new Twitter CE0",
  "Tiwa Savage at King Charles' Coronation",
  "Lecturers on the chat GPT spree",
  "Uyo fashion week 2023",
  "Afang vs Egusi",
  "NCC announces unified code for all telecom networks",
  "Harry Styles Grammy award 2023 ",
  "MET GALA 2023 ",
  "Avatar the way of water ",
  "FG on Compulsory primary education using native dialect",
  "Cholera crisis in the North",
  "US relaxes travel restrictions",
  "Neil Armstrong's exploit on the moon",
];
// ask chat gpt to generate code that fetches topics from the a tag in H3 in your html and fix them into the suggestions box while providing the direct links to where the topics are in the article page
